### ISSUE TITLE
create polling mode

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/judge-api#16]
for `POST /api/run` an extra body parameter called `mode` 

Possible values of mode are - 

 - sync
 - poll
 - callback

### For sync mode

 - current mode of operation
 - request is held till judgement is over, and then response is sent

### Poll mode

 - on request, we create a new job id
 - send the job id in the response
 - when judgement is over, in db, update the job status to done
 - client can continuosly request status of job via job id
 - `GET /api/run/:jobid` 
   - responds `status: running` till it is incomplete
   - responses `status: success` or `status: error` with output and error base64 when done

### callback mode (or webhook mode)

 - request body will contain a `callbackUrl` param also
 - when job is done, judge will make a POST request to `callbackUrl`

**Comment by championswimmer** [comment]
For callback and poll mode, we need to save the outputs to a S3 bucket file and keep the path in the database too 

The Submissions model needs to be updated accordingly for that.

**Comment by championswimmer** [comment]
use this to run dummy s3 server https://www.npmjs.com/package/s3rver

**Comment by abhishek97** [comment]
@championswimmer I propose the api should also have a `encodingType` body parameter to determine the encoding for the source and input values. For now we will support `base64` and `url`

**Comment by championswimmer** [comment]
`enc` (default: base64)

**Comment by abhishek97** [comment]
Submissions
```
output    Array:string    An array containg link to outputs
```
Will be storing `{submissionId}.json` files on s3 with the result recieved on success queue.
