### ISSUE TITLE
add support for Project Submissions

### ISSUE THREAD

**Issue by jatinkatyal13** [coding-blocks/judge-api#59]
Add support to run project submissions in frameworks like react, node, django etc.

Check [this](https://github.com/coding-blocks/judge-taskmaster/issues/36) issue on `judge-taskmaster` 

- Create a new API endpoint `/api/project`
  - [ ] Create `routes/api/project` directory
  - [ ] Write validator to support following request payload
  ```
  {
    "problem": <problem zip url>,
    "submission": <submission zip url>,
    "lang": <language>,
    "submissionDirs": <directories that can be editted>,
    "timelimit" <timelimit in seconds>,
    "mode": "sync" | "poll" | "callback",
    "callback": <if mode is callback then url>
  }
  ```
  - [ ] Send job to queue required by judge-taskmaster
  - [ ] Implement `onSuccess` listener on the controller

**Comment by imrishabh18** [comment]
@jatinkatyal13 Can i take up this issue ?

**Comment by jatinkatyal13** [comment]
@imrishabh18 Sure !

**Comment by saloniankita** [comment]
Is anyone working on this issue ?

**Comment by prabalsingh24** [comment]
I am working on this :)

**Comment by prabalsingh24** [comment]
@jatinkatyal13 Did you miss `lang` in the `payload`? 

and `submissionDirs` is an array of string right?

**Comment by prabalsingh24** [comment]
Also looking at [Job Class](https://github.com/coding-blocks/judge-taskmaster/blob/78a3cbb99baa3e3e9fddb4cfb6240c0d7dece5e8/src/tasks/job.ts#L31), is `submission` gonna be mapped with `source` because I don't see `submission` in [ProjectJob Class](https://github.com/coding-blocks/judge-taskmaster/blob/78a3cbb99baa3e3e9fddb4cfb6240c0d7dece5e8/src/tasks/job.ts#L58) but there is a `source`

**Comment by jatinkatyal13** [comment]
@prabalsingh24 yes, updated the issue. 

The Job base class handles the source and each of the scenarios handles the submissions differently. Hence, the submissions table doesn't have source column. The persistence of source is handled by the broker (Rabbitmq) and submissions model is only used to track the status and result.
