### ISSUE TITLE
Replace Stdin-->input and Stdout-->output

### ISSUE THREAD

**Issue by prabalsingh24** [coding-blocks/judge-api#61]
In [task-master](https://github.com/coding-blocks/judge-taskmaster/blob/08503cf29c4d921880e9d91abe4bce8b31cd38e3/src/tasks/scenarios/submission.ts#L37), `testcases.input` is used whereas in [jude-api](https://github.com/coding-blocks/judge-api/blob/72944d1764f56a6c06af7b1a46c90cfd16872e7d/src/routes/api/submit/validators.ts#L35)  it is defined as `testcases[0].stdin` and `...stdout`

**Comment by prabalsingh24** [comment]
This is a bug right?
If yes, then I'd like to solve it :)

**Comment by jatinkatyal13** [comment]
Nice catch @prabalsingh24. I'm writing down the steps for the fix.

- [ ] Update submit validator to accept the following format
    `{ id: <number>, input: <string>, output: <string> }`
    all the keys are required
- [ ] Update [Base Validator](https://github.com/coding-blocks/judge-api/blob/master/src/validators/baseValidator.ts#L23) to NOT accept unknown keys
- [ ] Test your PR through a mock request with following payload
    ```
    {
	"source": "I2luY2x1ZGUgPGlvc3RyZWFtPgogICAgICB1c2luZyBuYW1lc3BhY2Ugc3RkOwogICAgICBpbnQgbWFpbiAoKSB7CiAgICAgICAgICBjaGFyIGluWzEwXTsKICAgICAgICAgIGNpbj4+aW47CiAgICAgICAgICBjb3V0PDwiSGVsbG8gIjw8aW47CiAgICAgICAgICByZXR1cm4gMDsKICAgICAgfQ==",
	"lang": "cpp",
	"testcases": [{
        "id": 1,
        "input": "https://minio.cb.lk/public/input",
        "output": "https://minio.cb.lk/public/output"
      }]
    }
    ```

**Comment by prabalsingh24** [comment]
I am fixing this in [chai-mocha tests](https://github.com/coding-blocks/judge-api/pull/60),
Will save the trouble of rebasing and testing will be done then and there too :p

But if you want a different PR for that, I'll do that in a different PR
