### ISSUE TITLE
SubmitValidator Class Name is Wrong

### ISSUE THREAD

**Issue by prabalsingh24** [coding-blocks/judge-api#62]
[SubmitValidator Class](https://github.com/coding-blocks/judge-api/blob/72944d1764f56a6c06af7b1a46c90cfd16872e7d/src/routes/api/submit/validators.ts#L5) 's name is wrong

**Comment by shivam-bit** [comment]
is it still available? I would like to fix it

**Comment by prabalsingh24** [comment]
> is it still available? I would like to fix it

I am afraid no. PR's been approved

**Comment by joeedwin** [comment]
close the issue
@prabalsingh24

**Comment by prabalsingh24** [comment]
> close the issue
> @prabalsingh24

i thought @jatinkatyal13 will be closing this

**Comment by jatinkatyal13** [comment]
I'll close the issue once an acceptable PR is merged
