### ISSUE TITLE
Validators should check the validity of the language (lang) passed

### ISSUE THREAD

**Issue by prabalsingh24** [coding-blocks/judge-api#65]
[RunValidator](https://github.com/coding-blocks/judge-api/blob/72944d1764f56a6c06af7b1a46c90cfd16872e7d/src/routes/api/run/validators.ts#L14) and [SubmitValidator](https://github.com/coding-blocks/judge-api/blob/72944d1764f56a6c06af7b1a46c90cfd16872e7d/src/routes/api/submit/validators.ts#L14) both should  check if the `lang` is a correct language.

**Comment by championswimmer** [comment]
definitely!

**Comment by prabalsingh24** [comment]
how do you think this should be done. Checking everytime in the DB is costly I think. The languages can be hard coded or imported from a file (since there is only a small amount of them )?

**Comment by championswimmer** [comment]
Each submission will anyway involve db calls. A select on langs is pretty cheap. We can check on db each time.
