### ISSUE TITLE
Add polling endpoint

### ISSUE THREAD

**Issue by jatinkatyal13** [coding-blocks/judge-api#74]
We need to create an endpoint where user can poll for the submissions that were made using polling mode. All the jobs are stored in the `src/models/Submission` model which has a result key. While polling the user will give us the submission id and we'll return the submission object

- [ ] create a new folder `src/routes/api/submissions`
    - [ ] create an `index.ts` file which'll act as the url map
    - [ ] create an `controller.ts` file which'll export an object containing the handler
    - [ ] mount `/api/submissions/:id` endpoint to the polling controller
- [ ] write test for the api
    - [ ] Test if the API fives 403 if the api key is not provided or incorrect
    - [ ] Test if the API gives 404 if submission id not found
    - [ ] Test if the API gives returns the serialized submission model
    - [ ] update the test [here](https://github.com/coding-blocks/judge-api/blob/master/test/e2e/RunScenario.spec.ts#L157) and [here](https://github.com/coding-blocks/judge-api/blob/master/test/e2e/SubmitScenario.spec.ts#L158)

**Comment by SiddharthaMishra** [comment]
I'd like to work on this thanks!

**Comment by jatinkatyal13** [comment]
@SiddharthaMishra sure! 🚀

**Comment by MohdImran001** [comment]
@jatinkatyal13 Please tell me if we need to make use of RabbitMQ in this endpoint ?

**Comment by jatinkatyal13** [comment]
@MohdImran001 nope you won't be requiring rabbitmq for this endpoint

**Comment by SiddharthaMishra** [comment]
Hi, I was under the impression you were assigned issues but it seems like someone rushed a PR already. Is it the case the first guy to create a valid PR gets the points?
